services:

  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    ports: 
      - "8200:32400" 
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - VERSION=docker
      - PLEX_CLAIM=       #optional
    volumes:
      - ./config:/config
      - ./tvseries:/tv
      - ./movies:/movies
      - ./media:/data 
    restart: unless-stopped
